// File generated by FlutterFire CLI & configured for LabAi
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9kn7dy0NLU58LWhwGzYadnzxnqK1jP0Q',
    appId: '1:440857055374:web:9b4c3fc4ec5c63272df9df',
    messagingSenderId: '440857055374',
    projectId: 'labai-38839',
    authDomain: 'labai-38839.firebaseapp.com',
    storageBucket: 'labai-38839.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9kn7dy0NLU58LWhwGzYadnzxnqK1jP0Q',
    appId: '1:440857055374:android:9b4c3fc4ec5c63272df9df',
    messagingSenderId: '440857055374',
    projectId: 'labai-38839',
    storageBucket: 'labai-38839.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9kn7dy0NLU58LWhwGzYadnzxnqK1jP0Q',
    appId: '1:440857055374:ios:9b4c3fc4ec5c63272df9df',
    messagingSenderId: '440857055374',
    projectId: 'labai-38839',
    storageBucket: 'labai-38839.firebasestorage.app',
    iosBundleId: 'com.example.aiLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9kn7dy0NLU58LWhwGzYadnzxnqK1jP0Q',
    appId: '1:440857055374:ios:9b4c3fc4ec5c63272df9df',
    messagingSenderId: '440857055374',
    projectId: 'labai-38839',
    storageBucket: 'labai-38839.firebasestorage.app',
    iosBundleId: 'com.example.aiLab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9kn7dy0NLU58LWhwGzYadnzxnqK1jP0Q',
    appId: '1:440857055374:web:9b4c3fc4ec5c63272df9df',
    messagingSenderId: '440857055374',
    projectId: 'labai-38839',
    authDomain: 'labai-38839.firebaseapp.com',
    storageBucket: 'labai-38839.firebasestorage.app',
  );
}
